services:
  funky-monkey-friday:
    build: .
    container_name: funky_monkey_friday
    restart: unless-stopped
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
    volumes:
      # Map bot files (persistence)
      - .:/app
      
      # Map to the Pi's timezone settings (Sync Time)
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro